// index.js
//
// 2015-04-08, Jeremy Tammik, Autodesk Inc.
//
// Generated by Heroku node-js-getting-started.
// Added svg_01 implementation.

var svg_template = '\
<svg width="3cm" height="3cm" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" version="1.1">\
<rect x="1" y="1" width="98" height="98" fill="none" stroke="blue" stroke-width="3" />\
<path d="{path_data}" fill="red" stroke="blue" stroke-width="3" />\
</svg>';

var express = require('express');
var url = require('url');

var app = express();

app.set('port', (process.env.PORT || 5000));

app.get('/', function(request, response) {
  var paramdict = url.parse(request.url,true).query;
  if( !paramdict.hasOwnProperty('w') )
  {
    response.writeHead(400, {'Content-Type': 'text/plain'});
    response.end('No width specified');
  }
  if( !paramdict.hasOwnProperty('h') )
  {
    response.writeHead(400, {'Content-Type': 'text/plain'});
    response.end('No height specified');
  }
  else if( !paramdict.hasOwnProperty('d') )
  {
    response.writeHead(400, {'Content-Type': 'text/plain'});
    response.end('No SVG path description given');
  }
  else
  {
    var w = paramdict['w'];
    var h = paramdict['h'];
    var d = paramdict['d'];
    var svg = svg_template.replace('{path_data}', d);
    response.writeHead(200, {'Content-Type': 'text/html'});
    response.end(svg);
  }
});

app.listen(app.get('port'), function() {
  console.log("Node app is running at localhost:" + app.get('port'));
});
